/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#181919',
        'on-primary': '#ffffff',
        'primary-container': '#2d2d2d',
        'on-primary-container': '#959494',
        'primary-fixed': '#e4e2e1',
        'primary-fixed-dim': '#c8c6c6',
        'on-primary-fixed': '#1b1c1c',
        'on-primary-fixed-variant': '#474747',
        secondary: '#755844',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffd8be',
        'on-secondary-container': '#7a5c48',
        'secondary-fixed': '#ffdcc5',
        'secondary-fixed-dim': '#e5bfa6',
        'on-secondary-fixed': '#2b1707',
        'on-secondary-fixed-variant': '#5b412e',
        tertiary: '#181916',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#2d2d2a',
        'on-tertiary-container': '#959490',
        'tertiary-fixed': '#e4e2dd',
        'tertiary-fixed-dim': '#c8c6c2',
        'on-tertiary-fixed': '#1b1c19',
        'on-tertiary-fixed-variant': '#474744',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#fdf8f8',
        'surface-bright': '#fdf8f8',
        'surface-dim': '#ddd9d8',
        'surface-container': '#f1edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-container-low': '#f7f3f2',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#5f5e5e',
        'surface-variant': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#444748',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f4f0ef',
        'inverse-primary': '#c8c6c6',
        outline: '#747878',
        'outline-variant': '#c4c7c7',
        background: '#fdf8f8',
        'on-background': '#1c1b1b',
        walnut: '#6B4F3B',
        gold: '#C5A059',
        charcoal: '#181919',
        'muted-sage': '#E5E1D8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-gap': '120px',
        unit: '8px',
        'container-max': '1280px',
        'stack-lg': '64px',
        'stack-md': '32px',
        'stack-sm': '16px',
        'margin-mobile': '20px',
        'margin-desktop': '80px',
        gutter: '24px',
      },
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        button: ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        button: ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
